version: "3.7"
services:
  api_service:
    image: "web-app-with-db:v1"
    restart: always
    ports:
      - 8080:9999
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
      - spring.datasource.password=root
      - spring.datasource.username=root
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0.35"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: basics
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net: